// Main Entry point of our application, all component are wrapped within it as its children
// https://nextjs.org/docs/pages/building-your-application/routing/pages-and-layouts#layout-pattern
// If you want to add something which is consistent throughout the page, you should add it here. Like - redux toolkit,etc 
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
